name: 'transit_dbt'
version: '1.0.0'
config-version: 2

profile: 'transit_dbt'

model-paths: ["models"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  transit_dbt:
    staging:
      +schema: "{{ target.schema }}"
      +materialized: view
    marts:
      +schema: "{{ target.schema }}"
      +materialized: table